### ISSUE TITLE
pre-trained models from publication

### ISSUE THREAD

**Issue by igwill** [xzenglab/TAGPPI#6]
Hello,
I am interested in running TAGPPI prediction on a list of possible PPIs to compare to a results I obtained using a different machine learning tool. Are there trained-model files available that can be used to run such a "quick check" analysis without training a new model myself? The multi-species dataset model presented in the publication would be the most interesting for me, but could make due with the yeast model. (I've downloaded these datasets, but having an already trained and cross-validated model would be really great).

From there, as I understand, I would to use SeqVec separately to generate embeddings for my test data (or is this integrated in the TAGPPI pipeline?). Then, could you please outline which .py scripts I would need to run and which variables need to be set in them to make predictions on my test PPI pairs using the multi-species trained model? (I think all I will need in the end is the 1. trained model file, 2. protein embeddings, 3. a pairwise tsv of each PPI I wish to test, with names matching the input fasta to SeqVec?) I see some comments in the py files, but how exactly to use the tool isn't entirely clear to me.

Thank you for the help!

**Comment by igwill** [comment]
I have this running to attempt to recreate the published yeast model. However am receiving an error that might relate to the protein embeddings:

```
Running EPOCH 1
Traceback (most recent call last):
  File "my_main.py", line 25, in <module>
    main()
  File "my_main.py", line 22, in main
    train(trainArgs)
  File "/lustre/fs0/home/iwill/TAGPPI/TAGPPI-main/my_train_and_validation.py", line 54, in train
    for batch_idx,(G1,dmap1,G2,dmap2,y) in enumerate(train_loader):
  File "/home/iwill/my-envs/tagppi_3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/iwill/my-envs/tagppi_3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/iwill/my-envs/tagppi_3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/iwill/my-envs/tagppi_3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/lustre/fs0/home/iwill/TAGPPI/TAGPPI-main/graph_cmap_loader.py", line 74, in __getitem__
    G2,embed2 = self.loader(cmaproot+p2+'.npz',p2)
  File "/lustre/fs0/home/iwill/TAGPPI/TAGPPI-main/graph_cmap_loader.py", line 42, in default_loader
    G.ndata['feat'] = g_embed
  File "/home/iwill/my-envs/tagppi_3/lib/python3.7/site-packages/dgl/view.py", line 99, in __setitem__
    self._graph._set_n_repr(self._ntid, self._nodes, {key: val})
  File "/home/iwill/my-envs/tagppi_3/lib/python3.7/site-packages/dgl/heterograph.py", line 4033, in _set_n_repr
    ' Got %d and %d instead.' % (nfeats, num_nodes))
dgl._ffi.base.DGLError: Expect number of features to match number of nodes (len(u)). Got 205 and 255 instead.
```
I added some code to print out some more info as the function runs to see the node/feature mismatch:
```
nodenum is 59
g_embed length is 59
g_embed is tensor([[-0.3556, -0.1379, -0.0917,  ..., -0.2526, -0.0242,  0.3453],
        [-0.2281,  0.2757, -0.1602,  ..., -0.2342, -0.0326,  0.1073],
        [-0.0355, -0.1601,  0.0321,  ..., -0.2930,  0.1983, -0.1177],
        ...,
        [-0.0265,  0.0224, -0.3109,  ..., -0.2147, -0.0951, -0.0090],
        [ 0.2207,  0.0904,  0.0844,  ...,  0.0323, -0.0259, -0.1708],
        [-0.1693,  0.3720, -0.1931,  ...,  0.0684, -0.2738, -0.1622]])
pid is P81450
G isGraph(num_nodes=59, num_edges=891,
      ndata_schemes={}
      edata_schemes={})
nodenum is 295
g_embed length is 295
g_embed is tensor([[-0.3399, -0.0940, -0.0824,  ..., -0.0480,  0.1147,  0.1128],
        [ 0.2022,  0.2139,  0.1005,  ...,  0.2424,  0.0260, -0.1995],
        [ 0.1819, -0.0007, -0.1988,  ..., -0.0266,  0.0773, -0.1405],
        ...,
        [-0.3939, -0.2824, -0.1768,  ...,  0.0194, -0.0387, -0.0707],
        [-0.4689, -0.4695, -0.0849,  ..., -0.2983,  0.2909, -0.1734],
        [-0.5129, -0.2805, -0.4166,  ...,  0.1559, -0.1940, -0.1230]])
pid is P32573
G isGraph(num_nodes=292, num_edges=9518,
      ndata_schemes={}
      edata_schemes={})
Traceback (most recent call last):...........#error as shown above#
```
Removing that specific protein (P32573) and all its PPIs from the training pairs eventually shows another protein giving a similar error. I used the provided yeast alphafold cmap and dictionary.tsv (converted to fasta and then I ran Seqvec). Where do you think the problem lies - dependency environment (I've tried many), tagppi code, or embedding files?
When I try using the provided multi-spp data instead, I do not get this error, but get a different one (#7 ). This might indicate a problem with embedding files? Seqvec doesn't offer too many parameters to change, but any details there? Or could the hosted alphafold data be somehow incorrect?

Thank you

**Comment by ranzhran** [comment]
Did you solve this problem? and how did you solve it? Thank you!

**Comment by igwill** [comment]
I never went back to the yeast data, I just continued with the multi-spp data. There were other issues unrelated to this protein embedding thing that we worked around by editing the python script and how training works. Which all is a little suspicious (either a code bug or we don't have the expertise to use the tool correctly), so we've stopped working with TagPPI.
